on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release_windows

jobs:
  build:
    name: Upload Release Asset
    runs-on: [windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          vcpkg install boost openssl curl[openssl]  
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: ./ci_build.cmd  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Release/glean.exe
          asset_name: Glean Windows
          asset_content_type: application/exe
